v3.0 - dogs release

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,10 +1,3 @@
-name: Deploy to EC2
-
-on:
-  push:
-    branches:
-      - main
-
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -19,22 +12,53 @@ jobs:
           chmod 600 key.pem
 
       - name: Deploy
+        env:
+          TAG_NAME: ${{ github.ref_name }}
         run: |
-          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-          
+          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
+
           cd ~/aws-s3-ec2-rds-cicd
-          
-          git pull origin main
-          
+
+          echo "Fetching tags..."
+          git fetch --tags
+
+          echo "Saving current version..."
+          git rev-parse HEAD > prev_commit.txt
+
+          echo "Deploying tag: $TAG_NAME"
+          git checkout $TAG_NAME
+
           npm install
-          
           npm run build
 
-          echo "Running migrations..."
-          npm run migration:run 
-          
-          echo "Restarting app..."
+          npm run migration:run
+
           pm2 delete nest-app || true
           pm2 start ecosystem.config.js
-          
+
+          echo "Health check..."
+          sleep 5
+
+          for i in {1..5}; do
+            curl -f http://localhost:3000/health && break
+            sleep 2
+          done || (
+
+            echo "Deployment failed. Rolling back..."
+
+            npm run migration:revert
+
+            git checkout $(cat prev_commit.txt)
+
+            npm install
+            npm run build
+
+            pm2 delete nest-app || true
+            pm2 start ecosystem.config.js
+
+            exit 1
+          )
+
+          echo "Deployment successful!"
+
           EOF
