new feature

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
+      - name: Checkout (just for pipeline context)
         uses: actions/checkout@v4
 
       - name: Setup SSH
@@ -18,7 +18,7 @@ jobs:
           echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
           chmod 600 key.pem
 
-      - name: Deploy
+      - name: Deploy to EC2
         env:
           TAG_NAME: ${{ github.ref_name }}
         run: |
@@ -26,37 +26,74 @@ jobs:
 
           cd ~/aws-s3-ec2-rds-cicd
 
+          echo "=== Fetching latest tags ==="
           git fetch --tags
 
-          git rev-parse HEAD > prev_commit.txt
+          echo "=== Moving to deployment folder ==="
+          cd deployment
 
+          echo "=== Saving previous version ==="
+          if [ -f current_version.txt ]; then
+            cp current_version.txt previous_version.txt
+          fi
+
+          echo "Previous version:"
+          cat previous_version.txt || echo "None"
+
+          echo "=== Deploying new version: $TAG_NAME ==="
+          cd ~/aws-s3-ec2-rds-cicd
           git checkout $TAG_NAME
 
+          echo "$TAG_NAME" > deployment/current_version.txt
+
+          echo "=== Installing dependencies ==="
           npm install
+
+          echo "=== Building app ==="
           npm run build
 
+          echo "=== Running migrations ==="
           npm run migration:run
 
+          echo "=== Restarting app ==="
           pm2 delete nest-app || true
           pm2 start ecosystem.config.js
 
+          echo "=== Health check ==="
           sleep 5
 
           curl -f http://localhost:3000/health || (
 
-            echo "Rollback triggered"
+            echo "❌ Deployment failed. Rolling back..."
 
+            echo "Reverting DB..."
             npm run migration:revert
 
-            git checkout $(cat prev_commit.txt)
+            echo "Rolling back code..."
+            cd deployment
+            PREV_VERSION=$(cat previous_version.txt)
 
+            cd ~/aws-s3-ec2-rds-cicd
+            git checkout $PREV_VERSION
+
+            echo "Restoring version file..."
+            echo "$PREV_VERSION" > deployment/current_version.txt
+
+            echo "Re-installing..."
             npm install
+
+            echo "Re-building..."
             npm run build
 
+            echo "Restarting app..."
             pm2 delete nest-app || true
             pm2 start ecosystem.config.js
 
+            echo "Rollback completed"
+
             exit 1
           )
+
+          echo "✅ Deployment successful"
 
           EOF
